# Generated by Django 4.1 on 2022-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesandseries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="publicaton_date",
            field=models.DateField(),
        ),
    ]
